name: Trigger Daily Open na WEDOS

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Zavolej WEDOS skript
        run: |
          curl -s -w "\nHTTP status: %{http_code}\n" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml" \
            "https://svet-vyrezu.cz/Dpo/Dpowedos.php"
