name: Trigger Daily Open na WEDOS

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Zavolej WEDOS skript
        run: |
          curl -s -w "\nHTTP status: %{http_code}\n" "https://svet-vyrezu.cz/dpo/Dpowedos.php"
